---
# tekton/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipeline-sa
  namespace: cicd
  labels:
    app.kubernetes.io/part-of: ecommerce-cicd
secrets:
  - name: harbor-push-secret
  - name: git-ssh-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-sa
  namespace: cicd
  labels:
    app.kubernetes.io/part-of: ecommerce-cicd
